"""Generate the submitted-format Example-3 table from revised result CSVs."""
from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "results" / "revised"
PAPER_DIR = HERE.parents[1] / "paper_revision" / "revised_paper" / "exampleWH"
PAPER_TABLE = PAPER_DIR / "es3_table_new.tex"
PAPER_TABLE_REDUCED = PAPER_DIR / "es3_table_new_reduced.tex"


def read(path):
    with path.open() as stream:
        return list(csv.DictReader(stream))


def value(row, matlab_name, python_name):
    return row.get(matlab_name, row.get(python_name))


def architecture_order(family, row):
    if family in ("FL-CMO NNOE", "Batched NNOE"):
        return 3
    widths = [int(item) for item in row["hidden"].split("x")]
    return sum(widths) * (2 if family == "LSTM" else 1)


def block(family, method, rows, is_flcmo=False):
    best = max(range(len(rows)), key=lambda index: float(value(
        rows[index], "meanTestBFR", "mean_test_bfr")))
    count_label = "iterations" if is_flcmo else "epochs"
    unit_label = "time/iter" if is_flcmo else "time/epoch"
    lines = [
        r"    \hline",
        rf"    \multicolumn{{4}}{{|c|}}{{\multirow{{2}}[2]{{*}}{{\textbf{{{family} network}}}}}} & \multicolumn{{5}}{{c|}}{{\multirow{{2}}[2]{{*}}{{\textbf{{Training: {method}}}}}}} & \multicolumn{{4}}{{c|}}{{\multirow{{2}}[2]{{*}}{{\textbf{{Held-out test}}}}}} \\",
        r"    \multicolumn{4}{|c|}{} & \multicolumn{5}{c|}{} & \multicolumn{4}{c|}{} \\",
        r"    \hline",
        rf"    \textbf{{order}} & \textbf{{layers}} & \textbf{{units/layer}} & \textbf{{\# param.}} & \textbf{{RMSE $y_1$}} & \textbf{{RMSE $y_2$}} & \textbf{{{count_label}}} & \textbf{{time}} & \textbf{{{unit_label}}} & \textbf{{RMSE $y_1$}} & \textbf{{RMSE $y_2$}} & \textbf{{BFR $y_1$}} & \textbf{{BFR $y_2$}} \\",
        r"    \hline",
    ]
    previous_layers = None
    for index, row in enumerate(rows):
        layers = int(row["layers"])
        if previous_layers is not None and layers != previous_layers:
            lines.append(r"    \hline")
        previous_layers = layers
        epochs = int(float(value(row, "iterations", "epochs")))
        seconds = float(value(row, "trainingSeconds", "training_seconds"))
        per_iteration = float(value(row, "secondsPerIteration", "seconds_per_epoch"))
        fields = [
            f"{architecture_order(family, row)}", f"{layers}", row["hidden"].replace("x", ","),
            value(row, "parameters", "parameters"),
            f'{float(value(row, "trainingRMSE1", "training_rmse1")):.4f}',
            f'{float(value(row, "trainingRMSE2", "training_rmse2")):.4f}',
            f"{epochs}", f"{seconds:.2f}", f"{per_iteration:.4f}",
            f'{float(value(row, "testRMSE1", "test_rmse1")):.4f}',
            f'{float(value(row, "testRMSE2", "test_rmse2")):.4f}',
            f'{float(value(row, "testBFR1", "test_bfr1")):.2f}\%',
            f'{float(value(row, "testBFR2", "test_bfr2")):.2f}\%',
        ]
        prefix = r"    \rowcolor{green} " if index == best else "    "
        lines.append(prefix + " & ".join(fields) + r" \\")
    lines.extend([
        r"    \hline",
        r"    \multicolumn{1}{c}{} & & & \multicolumn{1}{c}{} & & & & & \multicolumn{1}{c}{} & & & & \\",
    ])
    return lines


def render(flcmo, families, reduced=False):
    qualifier = (" The weakest FL-CMO configurations are omitted for space."
                 if reduced else "")
    # Both alternatives use the same label so switching requires changing only
    # the input filename; they are never intended to be included together.
    label = "tab:wh_example_full_new"
    lines = [
        r"% Generated by code_new/Example3_MIMOWienerHammerstein/generate_revised_table.py",
        r"\begin{table*}", r"  \centering", r"  \renewcommand{\arraystretch}{0.78}",
        r"  \caption{Example 3: Comparison of networks for the identification of the MIMO Wiener--Hammerstein system. The two smallest architectures of each family are omitted." + qualifier + r" Training and test RMSEs, actual optimization iterations or epochs, total time in seconds, time per iteration or epoch, and held-out test BFR are reported. Green rows have the largest mean test BFR within each family. Adam methods use batches of 265 subsequences, each truncated to 128 samples.}",
        r"  \resizebox{\textwidth}{!}{\begin{tabular}{|cccc|ccccc|cccc|}",
    ]
    lines += block("FL-CMO NNOE", "FL-CMO, $K=1$ (CPU)", flcmo, True)
    lines += block("LSTM", "Adam BPTT (CPU)", families["LSTM"])
    lines += block("GRU", "Adam BPTT (CPU)", families["GRU"])
    lines += block("Batched NNOE", "Adam truncated BPTT (CPU)", families["Batched NNOE"])
    lines += [r"    \bottomrule", r"  \end{tabular}}", rf"  \label{{{label}}}", r"\end{table*}"]
    return "\n".join(lines) + "\n"


def main():
    # The first two (smallest) architectures of every family are omitted
    # from the revised comparison, as requested after the final CMO rerun.
    flcmo = read(OUT / "nnoe_all_paper_models.csv")[2:]
    adam = read(OUT / "python_all_paper_models.csv")
    families = {name: [row for row in adam if row["model"] == key][2:] for name, key in (
        ("LSTM", "LSTM"), ("GRU", "GRU"), ("Batched NNOE", "NNOE_BATCHED"))}
    text = render(flcmo, families)
    # Drop only clearly weak FL-CMO rows in the space-saving version.
    compact_flcmo = [row for row in flcmo
                     if float(value(row, "meanTestBFR", "mean_test_bfr")) >= 80]
    reduced = render(compact_flcmo, families, reduced=True)
    (OUT / "table_example3_new.tex").write_text(text)
    (OUT / "table_example3_new_reduced.tex").write_text(reduced)
    PAPER_TABLE.write_text(text)
    PAPER_TABLE_REDUCED.write_text(reduced)


if __name__ == "__main__":
    main()
