"""MIMO_LSTM_identification.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ta8zm3fI5xrAP3BaDTEXmoSWI3kLsrm0

Simone Pirrera

Oct 26, 2022

## Training of a recurrent neural network (RNN) to perform nonlinear system identification.
"""

import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import layers
# import pandas as pd
import matplotlib.pyplot as plt
import time
import math
from statistics import mean

## Import data
import scipy.io as sio

# Load the .mat file
PATH_DATA = "C:\\Users\\simon\\Desktop\\NNOE SCRIPT and EXAMPLES\\data"
mat_contents = sio.loadmat(PATH_DATA + "\\dataset_training_03.mat")
utrain = mat_contents['utrain']
ytrain = mat_contents['ytrain']
Ntrain = 3500
utrain = utrain[0:Ntrain,:]
ytrain = ytrain[0:Ntrain,:]

dim_u = utrain.shape[1]
dim_y = ytrain.shape[1]

mat_contents = sio.loadmat(PATH_DATA + "//dataset_test_03.mat")
u_test = mat_contents['u_test']
y_test = mat_contents['y_test']

x_train = np.reshape(utrain,(1,utrain.shape[0],dim_u))
y_train = np.reshape(ytrain,(1,ytrain.shape[0],dim_y))

outfile = open('res03_gru.txt', 'a')

for num_units in [2,3]:
## Build RNN

    print(f"### Number of units: {num_units}", file=outfile)
    print(f"### Number of units: {num_units}")
    
    model = keras.Sequential()
    model.add(layers.GRU(input_shape=(None,dim_u),
                               return_sequences=True,
                               units=num_units,
                               activation='tanh'))
    model.add(layers.GRU(input_shape=(None,num_units),
                               return_sequences=True,
                               units=num_units,
                               activation='tanh'))
    model.add(layers.GRU(input_shape=(None,num_units),
                               return_sequences=True,
                               units=num_units,
                               activation='tanh'))
    model.add(layers.TimeDistributed(layers.Dense(activation='linear', units=dim_y)))
    model.build()
    model.summary()
    
    tot_param = np.sum([np.prod(v.get_shape()) for v in model.trainable_weights])
    print(f"Trainable parameters: {tot_param}", file=outfile)
    print(f"Trainable parameters: {tot_param}")

    # Model compilation
    model.compile(loss = 'mse', optimizer = 'adam')
    # Model training 
    starttime = time.time()
    model.fit(x_train, y_train, epochs = 12000, batch_size = 32)
    endtime = time.time()
    elapsed_time = endtime - starttime
    print(f"Elapsed time: {elapsed_time} seconds", file=outfile)
    print(f"Elapsed time: {elapsed_time} seconds")

    ## Test model and print results
    utest = np.reshape(u_test,(1,u_test.shape[0],dim_u))
    Ntest = u_test.shape[0];

    y_pred = model.predict(np.array(utest))
    t = [k for k in range(0,len(u_test))];
    #plt.plot(t,y_test)
    #plt.plot(t,y_pred[0,:,:])
    #plt.show()

    y_train_pred = model.predict(np.array(np.reshape(utrain,(1,utrain.shape[0],dim_u))))

    rmse1 = math.sqrt(sum((ytrain[:,0] - y_train_pred[0,:,0])**2))/math.sqrt(Ntrain)
    rmse2 = math.sqrt(sum((ytrain[:,1] - y_train_pred[0,:,1])**2))/math.sqrt(Ntrain)
    print('training rmse = ', rmse1, rmse2, file=outfile)
    print('training rmse = ', rmse1, rmse2)

    rmse1 = math.sqrt(sum((y_test[:,0] - y_pred[0,:,0])**2))/math.sqrt(Ntest)
    rmse2 = math.sqrt(sum((y_test[:,1] - y_pred[0,:,1])**2))/math.sqrt(Ntest)
    print('test rmse = ', rmse1, rmse2, file=outfile)
    print('test rmse = ', rmse1, rmse2)

    fit1 = 1-math.sqrt(rmse1**2 / (sum((y_test[:,0]-mean(y_test[:,0]))**2)/Ntest) )
    fit2 = 1-math.sqrt(rmse2**2 / (sum((y_test[:,1]-mean(y_test[:,1]))**2)/Ntest) )
    print('test fit = ', fit1, fit2, file=outfile)
    print('test fit = ', fit1, fit2)

    # A prompt for Yes/No/Cancel
    print("Saving predicted sequence to file...")
    np.savetxt("gru_test_3_"+str(num_units)+".csv", y_pred[0,:,:], delimiter=",")
    print("Done")
        
outfile.close()